// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickSurvey.Infrastructure;

namespace QuickSurvey.Infrastructure.Migrations
{
    [DbContext(typeof(SurveyContext))]
    [Migration("20210321013508_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.HasSequence("sessionseq")
                .IncrementsBy(10);

            modelBuilder.Entity("QuickSurvey.Core.SessionAggregate.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "sessionseq")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions", "quicksurvey");
                });

            modelBuilder.Entity("QuickSurvey.Core.SessionAggregate.Session", b =>
                {
                    b.OwnsMany("QuickSurvey.Core.Entities.Participant", "Participants", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("SessionId")
                                .HasColumnType("int");

                            b1.Property<string>("Username")
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.HasIndex("Username", "SessionId")
                                .IsUnique()
                                .HasFilter("[Username] IS NOT NULL");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsMany("QuickSurvey.Core.SessionAggregate.Choice", "Choices", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("SessionId")
                                .HasColumnType("int");

                            b1.Property<string>("Text")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Voters")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.HasIndex("Text", "SessionId")
                                .IsUnique()
                                .HasFilter("[Text] IS NOT NULL");

                            b1.ToTable("Choices");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Choices");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
