// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickSurvey.Infrastructure;

namespace QuickSurvey.Infrastructure.Migrations
{
    [DbContext(typeof(SurveyContext))]
    [Migration("20210320215216_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("QuickSurvey.Core.SessionAggregate.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("sessions", "quicksurvey");
                });

            modelBuilder.Entity("QuickSurvey.Core.SessionAggregate.Session", b =>
                {
                    b.OwnsMany("QuickSurvey.Core.Entities.Participant", "Participants", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SessionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Username")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.HasIndex("Username", "SessionId")
                                .IsUnique();

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsMany("QuickSurvey.Core.SessionAggregate.Choice", "Choices", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SessionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Voters")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.HasIndex("Text", "SessionId")
                                .IsUnique();

                            b1.ToTable("Choices");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Choices");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
